// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-shop/internal/model"
)

type (
	IRefund interface {
		Add(ctx context.Context, in model.AddRefundInput) (out model.AddRefundOutput, err error)
		List(ctx context.Context, in model.ListRefundInput) (out model.ListRefundOutput, err error)
		Detail(ctx context.Context, in model.DetailRefundInput) (out model.DetailRefundOutput, err error)
	}
)

var (
	localRefund IRefund
)

func Refund() IRefund {
	if localRefund == nil {
		panic("implement not found for interface IRefund, forgot register?")
	}
	return localRefund
}

func RegisterRefund(i IRefund) {
	localRefund = i
}
